"""Render a scan report as an HTML document a prospect can read.

The scan JSON is written for the operator: rule ids, file paths, line
numbers. Handed to a prospective client it reads as noise — and it also
tells them (and anyone they forward it to) exactly where every weakness is
before any engagement exists. So this renderer is not a reskin; it is an
editorial pass with two audiences in mind:

**The prospect sees categories and consequences, not coordinates.** Findings
are grouped by theme with a plain-language explanation of what each class of
problem costs. Counts and severities are real; file paths and line numbers
are withheld from the shareable body ("3 places" rather than which three).
The full technical detail is what the engagement buys. A teaser that gives
away the map is a free audit, and a teaser that names exact vulnerable lines
in a document designed to be forwarded is a liability for the *prospect*.

**Nothing is inflated.** Every number comes straight off the scan, the
severity scale is printed with its meaning, and a section that found nothing
says so. A lead generated by an exaggerated report becomes a client who
distrusts the first invoice. The honesty rules from the status page apply
here for commercial reasons as much as ethical ones.

Usage (after `agents scan <repo> --out report.json`):

    python -m agents.prospect_report report.json --company "Acme Inc" --out acme.html
"""

from __future__ import annotations

import argparse
import html
import json
import sys
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict

# Tool -> (theme, what this class of problem means to a business).
# A tool absent here lands in "Code quality & robustness" with generic copy.
THEMES: Dict[str, tuple[str, str]] = {
    "audit_hardcoded_secrets": (
        "Credential exposure",
        "Secrets committed to source code can be read by anyone who ever gains access to the repository — including former contractors and leaked laptop backups. Rotation is urgent once exposed.",
    ),
    "audit_env_example": (
        "Credential exposure",
        "Configuration templates and environment handling that leak or under-document credentials cause both breaches and failed deployments.",
    ),
    "check_jwt_implementation": (
        "Authentication weaknesses",
        "Flaws in how logins and sessions are verified can let attackers impersonate users without ever stealing a password.",
    ),
    "review_refresh_token_rotation": (
        "Authentication weaknesses",
        "Long-lived tokens that are never rotated stay valid after a device is lost or a session is stolen.",
    ),
    "audit_shared_secret_auth": (
        "Authentication weaknesses",
        "A single shared key protecting internal endpoints means one leak opens every door at once.",
    ),
    "review_apple_sign_in": (
        "Authentication weaknesses",
        "Social sign-in that skips server-side verification accepts forged identities.",
    ),
    "review_oauth_flow": (
        "Authentication weaknesses",
        "OAuth mistakes let attackers link their identity to someone else's account.",
    ),
    "review_biometric_auth": (
        "Authentication weaknesses",
        "Biometric checks done only on the client can be bypassed entirely.",
    ),
    "audit_sql_injection": (
        "Injection & data exposure",
        "Untrusted input reaching a database query is the classic route to a full data breach.",
    ),
    "audit_xss_patterns": (
        "Injection & data exposure",
        "Script injection lets an attacker run code in your users' browsers — stealing sessions or defacing pages.",
    ),
    "audit_input_validation": (
        "Injection & data exposure",
        "Unvalidated input reaching shell commands or eval is remote code execution waiting for a payload.",
    ),
    "audit_csrf_protection": (
        "Injection & data exposure",
        "Without CSRF protection, a malicious page can make logged-in users perform actions they never chose.",
    ),
    "audit_file_upload": (
        "Injection & data exposure",
        "Unrestricted uploads let attackers store and execute their own files on your infrastructure.",
    ),
    "audit_cors_config": (
        "Perimeter configuration",
        "An over-permissive CORS policy lets any website read your API responses on behalf of logged-in users.",
    ),
    "analyze_helmet_config": (
        "Perimeter configuration",
        "Missing security headers leave the browser's built-in defences switched off.",
    ),
    "audit_websocket_auth": (
        "Perimeter configuration",
        "Real-time channels that skip authentication accept messages from anyone.",
    ),
    "audit_rate_limiting": (
        "Perimeter configuration",
        "Without rate limits, credential-stuffing and scraping run at full speed.",
    ),
    "audit_workflow": (
        "Build & supply chain",
        "CI workflows with excess permissions or unpinned third-party steps are how attackers ship code as you.",
    ),
    "audit_dockerfile": (
        "Build & supply chain",
        "Container images running as root or built from unpinned bases widen every later compromise.",
    ),
    "audit_compose": (
        "Build & supply chain",
        "Development stacks that expose databases or bake in credentials tend to follow the project to production.",
    ),
    "scan_dependencies": (
        "Build & supply chain",
        "Known-vulnerable dependencies are the single most common initial foothold.",
    ),
    "audit_wrangler": (
        "Build & supply chain",
        "Secrets committed to platform config are plaintext in version control.",
    ),
    "audit_android_manifest": (
        "Mobile app hardening",
        "Manifest misconfigurations expose app data to other apps on the device or send traffic unencrypted.",
    ),
    "audit_ios_plist": (
        "Mobile app hardening",
        "Transport-security exceptions let a coffee-shop network read your users' traffic.",
    ),
    "audit_railway_config": (
        "Reliability & operations",
        "Health checks that point nowhere make outages invisible and deployments unreliable.",
    ),
    "audit_error_handling": (
        "Reliability & operations",
        "Raw errors returned to users leak internals and make debugging attacks easier.",
    ),
    "audit_logging_security": (
        "Reliability & operations",
        "Logging secrets or personal data turns every log archive into a breach in waiting.",
    ),
    "review_error_boundary_coverage": (
        "Reliability & operations",
        "A single component error should not blank the whole screen.",
    ),
    "review_sentry_setup": (
        "Reliability & operations",
        "Without error tracking, production failures surface as one-star reviews instead of alerts.",
    ),
    "validate_accessibility": (
        "Accessibility",
        "Accessibility gaps exclude users and, for many client industries, carry legal exposure (ADA/EAA).",
    ),
}
DEFAULT_THEME = (
    "Code quality & robustness",
    "Issues that make the codebase harder to change safely and more likely to break under real-world input.",
)

SEVERITY_ORDER = ["CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO"]
SEVERITY_MEANING = {
    "CRITICAL": "exploitable now, or credentials already exposed",
    "HIGH": "a real vulnerability or outage cause; fix soon",
    "MEDIUM": "weakens defences or reliability; schedule it",
    "LOW": "hygiene and hardening",
    "INFO": "worth knowing, no action forced",
}


def summarize(report: Dict[str, Any]) -> Dict[str, Any]:
    """Fold a scan report into theme buckets with real counts and no paths."""
    themes: Dict[str, Dict[str, Any]] = {}
    files_with_findings = set()
    severities: Counter = Counter()

    for entry in report.get("results", []):
        tool = entry.get("tool", "")
        findings = entry.get("result", {}).get("findings", [])
        if not findings:
            continue
        files_with_findings.add(entry.get("file", "?"))
        theme, meaning = THEMES.get(tool, DEFAULT_THEME)
        bucket = themes.setdefault(
            theme,
            {"meaning": meaning, "count": 0, "severities": Counter(), "files": set()},
        )
        for f in findings:
            sev = f.get("severity", "INFO")
            bucket["count"] += 1
            bucket["severities"][sev] += 1
            severities[sev] += 1
        bucket["files"].add(entry.get("file", "?"))

    coverage = report.get("coverage", {}) or {}
    return {
        "themes": themes,
        "severities": severities,
        "files_with_findings": len(files_with_findings),
        "files_scanned": coverage.get("files_scanned") or report.get("files_scanned"),
        "total": sum(severities.values()),
    }


def render_html(
    summary: Dict[str, Any], *, company: str, prepared_by: str = "Rushing Technologies"
) -> str:
    e = html.escape
    sev = summary["severities"]
    now = datetime.now(timezone.utc)

    sev_row = "".join(
        f'<div class="sev"><span class="n">{sev.get(s, 0)}</span><span class="l">{s.title()}</span>'
        f'<span class="m">{e(SEVERITY_MEANING[s])}</span></div>'
        for s in SEVERITY_ORDER
        if sev.get(s)
    )

    theme_blocks = []
    ordered = sorted(
        summary["themes"].items(),
        key=lambda kv: min(
            (SEVERITY_ORDER.index(s) for s in kv[1]["severities"]), default=99
        ),
    )
    for theme, data in ordered:
        counts = ", ".join(
            f"{data['severities'][s]} {s.lower()}"
            for s in SEVERITY_ORDER
            if data["severities"].get(s)
        )
        places = len(data["files"])
        theme_blocks.append(
            f"<section><h2>{e(theme)}</h2>"
            f"<p class='counts'>{data['count']} finding(s) — {e(counts)} — across {places} location(s).</p>"
            f"<p>{e(data['meaning'])}</p></section>"
        )
    if not theme_blocks:
        theme_blocks.append(
            "<section><h2>No findings</h2><p>The automated pass found nothing to flag. That speaks well of the codebase — though automated coverage is a floor, not a ceiling.</p></section>"
        )

    scanned = summary.get("files_scanned")
    scope = (
        f"{scanned} files analysed, findings in {summary['files_with_findings']}."
        if scanned
        else f"Findings in {summary['files_with_findings']} file(s)."
    )

    return f"""<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="robots" content="noindex">
<title>{e(company)} — Security &amp; Reliability Snapshot</title>
<style>
  :root{{--ink:#1a1a1a;--muted:#5f6368;--line:#e3e3e3;--accent:#0b5cad;--bg:#fff}}
  @media (prefers-color-scheme:dark){{:root{{--ink:#ececec;--muted:#a0a4a8;--line:#333;--accent:#6db3f2;--bg:#111}}}}
  *{{box-sizing:border-box}} body{{margin:0;background:var(--bg);color:var(--ink);font:16px/1.55 -apple-system,"Segoe UI",Roboto,Helvetica,Arial,sans-serif}}
  main{{max-width:720px;margin:0 auto;padding:48px 24px 64px}}
  header{{border-bottom:2px solid var(--accent);padding-bottom:16px;margin-bottom:12px}}
  h1{{font-size:1.5rem;margin:0 0 4px}} .sub{{color:var(--muted);margin:0}}
  .scope{{color:var(--muted);margin:16px 0 24px}}
  .sevrow{{display:flex;gap:14px;flex-wrap:wrap;margin:0 0 28px}}
  .sev{{border:1px solid var(--line);border-radius:10px;padding:10px 14px;min-width:120px}}
  .sev .n{{font-size:1.4rem;font-weight:700;display:block}} .sev .l{{font-weight:600}}
  .sev .m{{display:block;color:var(--muted);font-size:.8rem;margin-top:2px}}
  section{{margin:0 0 22px;padding-bottom:16px;border-bottom:1px solid var(--line)}}
  section:last-of-type{{border-bottom:0}}
  h2{{font-size:1.05rem;margin:0 0 6px}} .counts{{color:var(--muted);margin:0 0 8px;font-size:.95rem}}
  footer{{color:var(--muted);font-size:.85rem;margin-top:36px;border-top:1px solid var(--line);padding-top:16px}}
</style></head><body><main>
<header><h1>{e(company)}</h1><p class="sub">Security &amp; Reliability Snapshot · {now:%B %Y}</p></header>
<p class="scope">{e(scope)} Automated analysis; exact locations and remediation guidance are provided under an engagement.</p>
<div class="sevrow">{sev_row or '<p>No findings.</p>'}</div>
{"".join(theme_blocks)}
<footer>Prepared by {e(prepared_by)} · generated {now:%Y-%m-%d} · Counts are unmodified scanner output; a section with nothing to report is omitted rather than padded. This snapshot is a starting point, not a completed audit.</footer>
</main></body></html>"""


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Render a scan JSON as a prospect-facing HTML snapshot."
    )
    parser.add_argument(
        "report", help="Path to the JSON written by `agents scan --out`"
    )
    parser.add_argument("--company", required=True, help="Name to put on the document")
    parser.add_argument("--out", help="Output HTML path (default: <report>.html)")
    args = parser.parse_args()

    report = json.loads(Path(args.report).read_text(encoding="utf-8"))
    page = render_html(summarize(report), company=args.company)
    out = Path(args.out or (Path(args.report).with_suffix(".html")))
    out.write_text(page, encoding="utf-8")
    print(f"wrote {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
